# zizmor: ignore[unverified-uses]
# zizmor: ignore[unpinned-images]
# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow will run nightly or when triggered from PR comment

name: Generative API Examples

on: # zizmor: ignore[all]
  workflow_call:
    inputs:
      trigger-sha:
        required: true
        type: string

permissions: # zizmor: ignore[all]
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-examples:
    name: Check Examples
    runs-on: # zizmor: ignore[all]
      labels: linux-x86-n2-16
    container: # zizmor: ignore[all]
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build@sha256:12822904942562e7deb0c91fb0eb3dd9ec87b4292881108b166e44149422b87d # latest

    steps:
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4 # zizmor: ignore[all]
        with:
          python-version: "3.11"
      - uses: bazel-contrib/setup-bazel@b388b84bb637e50cdae241d0f255670d4bd79f29 # 0.8.1 # zizmor: ignore[all]
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: false
          # Share repository cache between workflows.
          repository-cache: false
      - uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1 # zizmor: ignore[all]
        id: setup-ndk
        with:
          ndk-version: r21e
          add-to-path: false
      - uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3 # zizmor: ignore[all]
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3 # zizmor: ignore[all]
      - run: |
          sdkmanager "build-tools;30.0.3" "platform-tools"
          sdkmanager "platforms;android-30" "extras;android;m2repository"
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3 # zizmor: ignore[all]
        with:
          ref: ${{ inputs.trigger-sha }}
          persist-credentials: false
      - name: Install python dependencies
        run: |
          pip3 install numpy
      - name: Build
        run: |
          ci/test_examples_build.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
