name: Zizmor Security Scan

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Run Zizmor Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results # zizmor: ignore[excessive-permissions]
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install zizmor
        run: pipx install zizmor

      - name: Run Zizmor
       
        run: zizmor --format sarif .github/workflows > zizmor-results.sarif

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@c4dd10e44af883a891fe31ced449bcb4a6728b9b # v3
        with:
          sarif_file: zizmor-results.sarif
          category: zizmor
